import { CLUSTER_LAYER_ID, CLUSTER_SOURCE_ID } from "../constants/layerIds.js";
import { CLUSTER_OPACITY_WITH_HEATMAP } from "../constants/renderConstants.js";

export const CLUSTER_LAYER = {
  id: CLUSTER_LAYER_ID,
  type: "circle",
  source: CLUSTER_SOURCE_ID,
  paint: {
    "circle-radius": [
      "interpolate",
      ["linear"],
      ["zoom"],
      3,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        2.5,
        500,
        4.5,
        5000,
        8.5,
        50000,
        17,
      ],
      5,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        3.5,
        500,
        7,
        5000,
        15,
        50000,
        28,
      ],
      7,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        5,
        500,
        13,
        5000,
        30,
        50000,
        44,
      ],
      10,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        7,
        500,
        22,
        5000,
        46,
        50000,
        64,
      ],
    ],
    "circle-color": [
      "interpolate",
      ["linear"],
      ["zoom"],
      3,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        "#a4e5dd",
        5000,
        "#5fcfc4",
        50000,
        "#2d9d97",
      ],
      7,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        "#42d6c4",
        500,
        "#18b7a8",
        5000,
        "#078f86",
        50000,
        "#045f67",
      ],
    ],
    "circle-opacity": CLUSTER_OPACITY_WITH_HEATMAP,
    "circle-blur": 0,
    "circle-stroke-color": "#ffffff",
    "circle-stroke-width": 2,
    "circle-stroke-opacity": 1,
  },
  layout: {
    visibility: "none",
  },
};

export const CLUSTER_LAYER_FALLBACK = {
  ...CLUSTER_LAYER,
  paint: {
    "circle-radius": 16,
    "circle-color": "#18b7a8",
    "circle-opacity": 0.9,
    "circle-blur": 0,
    "circle-stroke-color": "#ffffff",
    "circle-stroke-width": 2,
    "circle-stroke-opacity": 1,
  },
};
