import { CLUSTER_LAYER_ID, CLUSTER_SOURCE_ID } from "../constants/layerIds.js";

export const CLUSTER_LAYER = {
  id: CLUSTER_LAYER_ID,
  type: "circle",
  source: CLUSTER_SOURCE_ID,
  minzoom: 5,
  maxzoom: 13,
  
  paint: {
    "circle-radius": [
      "interpolate",
      ["linear"],
      ["zoom"],

      3,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        2,
        500,
        4,
        5000,
        7,
        50000,
        12,
      ],

      5,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        3,
        500,
        6,
        5000,
        10,
        50000,
        18,
      ],

      7,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        4,
        500,
        9,
        5000,
        15,
        50000,
        24,
      ],

      10,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        5,
        500,
        12,
        5000,
        20,
        50000,
        32,
      ],
    ],
    "circle-color": [
      "interpolate",
      ["linear"],
      ["zoom"],
      3,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        "#a4e5dd",
        5000,
        "#5fcfc4",
        50000,
        "#2d9d97",
      ],
      7,
      [
        "interpolate",
        ["linear"],
        ["get", "tower_count"],
        1,
        "#42d6c4",
        500,
        "#18b7a8",
        5000,
        "#078f86",
        50000,
        "#045f67",
      ],
    ],
    "circle-opacity": [
      "interpolate",
      ["linear"],
      ["zoom"],
      6,
      0,
      8,
      1,
      10,
      1,
      12,
      0,
    ],
    "circle-blur": ["interpolate", ["linear"], ["zoom"], 6, 0.12, 10, 0],
    "circle-stroke-color": "#ffffff",
    "circle-stroke-width": ["interpolate", ["linear"], ["zoom"], 6, 1, 10, 1.5],
    "circle-stroke-opacity": 1,
  },
  layout: {
    visibility: "visible",
  },
};
